ExpensApp/ExpensApp.Presentation/Controllers/ManagerController.cs
using CommonArea;
using ExpensApp.Business;
using ExpensApp.Presentation.Filter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExpensApp.Presentation.Controllers
{
    public class ManagerController : Controller
    {

        List<FormCommon> formList = new List<FormCommon>();
        List<EmployeeCommon> employeeList = new List<EmployeeCommon>();
        List<ExpenseCommon> expenseList = new List<ExpenseCommon>();
        ManagerBusiness manager = new ManagerBusiness();
        MultipleModel2 myModel = new MultipleModel2();
        MultipleModel3 myModel3 = new MultipleModel3();

        // GET: Manager
        [AuthFilter, AuthorityControlManager]
        public ActionResult ManagerMainPage()
        {
            return View();
        }
        // GET: Manager
        [AuthFilter, AuthorityControlManager]
        public ActionResult ManagerDetailPage(int FormId, int EmployeeId)
        {
            List<ExpenseCommon> expenseList2 = new List<ExpenseCommon>();
            EmployeeCommon employee = new EmployeeCommon();

            expenseList2 = manager.GetExpenses(FormId);
            employee = manager.GetSingleEmployee(EmployeeId);

            myModel3.listForExpenses = expenseList2;
            myModel3.employee = employee;

            return View(myModel3);
        }


        [AuthFilter, AuthorityControlManager]
        public ActionResult ApprovingExpenseFormPage()
        {
            formList = manager.GetForms();     //getting forms 
            employeeList = manager.GetEmployees(formList);   //getting employees

            myModel.listForForms = formList;
            myModel.listForEmployees = employeeList;

            return View(myModel);
        }

        [AuthFilter, AuthorityControlManager]
        public ActionResult OpenExpensePage(int formId)
        {
            expenseList = manager.GetExpenses(formId);
            return View(expenseList);
        }


        [AuthFilter, AuthorityControlManager]
        public ActionResult ManagerReportsPage()
        {
            List<FormCommon> formListAll = new List<FormCommon>();
            List<EmployeeCommon> employeeListAll = new List<EmployeeCommon>();
            MultipleModel2 myModel2 = new MultipleModel2();

            formListAll = manager.GetAllForms();
            employeeListAll = manager.GetEmployees(formListAll);

            myModel2.listForForms = formListAll;
            myModel2.listForEmployees = employeeListAll;

            return View(myModel2);
        }

        [HttpPost]
        [AuthFilter, AuthorityControlManager]
        public ActionResult UpdateForm()
        {
            int FormId = int.Parse(Request["FormId"]);
            string Status = Request["Status"];
            ExpenseCommon singleExpense = new ExpenseCommon();
            
            string newStatus = Status;

            manager.UpdateForm(FormId, Status);


            return null;
        }
    }
}

ExpensApp/ExpensApp.Presentation/Views/Manager/ApprovingExpenseFormPage.cshtml
@{
    Layout = null;
}
@model CommonArea.MultipleModel2

<!DOCTYPE html>

<html>
<head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="~/Content/css/GridSheetforFillExpenseFormPage.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>ApprovingExpenseFormPage</title>
</head>
<body>
    <div>
        <h1>ONAY BEKLEYEN MASRAF FORMLARI</h1>
    </div>

    <div class="container">
        <div class="row col-md-6 col-md-offset-2 custyle">
            <table class="table table-striped custab" id="formTable">
                <tr>
                    <th>Form Tarihi</th>
                    <th>Çalışan Ad Soyad</th>
                    <th>Toplam Masraf Tutarı</th>
                    <th>Aksiyonlar</th>
                </tr>
                @{
                    int counter = 0;
                    foreach (var item in Model.listForForms)
                    {
                        var item2 = Model.listForEmployees[counter];
                        
                            <tr id="@item.FormID">
                                <td>@item.Date.ToString("dd/MM/yyyy")</td>
                                <td>@item2.Name @item2.Surname</td>
                                <td>@item.TotalAmount</td>
                                <td><a class="btn btn-primary" href="@Url.Action("ManagerDetailPage", new { FormId = item.FormID, EmployeeId = item.EmployeeID })">Detay</a></td>
                            </tr>
                        
                    }
                }
            </table>
        </div>
    </div>
</body>
</html>

ExpensApp/ExpensApp.Presentation/Views/Manager/ManagerDetailPage.cshtml
@{
    Layout = null;
}
@model CommonArea.MultipleModel3

<!DOCTYPE html>

<html>
<head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="~/Content/css/GridSheetforFillExpenseFormPage.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>Detail</title>
</head>
<body>
    <div>
        <h1>MASRAF DETAY FORMLARI</h1>
    </div>
    <div>
        <p>Çalışan Adı ve Soyadı @Model.employee.Name @Model.employee.Surname</p>
        <p>Çalışan Email Adresi @Model.employee.Email</p>
    </div>

    @*Printing expenses and total amount to the screen*@
    @{
        int TotalAmount = 0;
        <p align="center"><b>Masraflar:</b></p>
                <div class="container">
                    <div class="row col-md-6 col-md-offset-2 custyle">
                        <table class="table table-striped custab">
                            <tr>
                                <th>Masraf Türü</th>
                                <th>Masraf Zamanı</th>
                                <th>Masraf Açıklaması</th>
                                <th>Masraf Tutarı</th>
                            </tr>
                            @foreach (var item in Model.listForExpenses)
            {
                                <tr>
                                    <td>@item.Type</td>
                                    <td>@item.Date.ToString("dd/MM/yyyy") </td>
                                    <td>@item.Explanation</td>
                                    <td>@item.Cost</td>
                                    @{
                                        TotalAmount += item.Cost;
                                    }
                                </tr>
                                        }
                        </table>
                    </div>
                </div>
    }
    <br /><p align="center"><b>Total Amount : @TotalAmount</b></p>
    <div>
        @using (Html.BeginForm("UpdateForm", "Manager", FormMethod.Post, new { FormId = Model.listForExpenses.First().FormID , Status = "Onaylandı" }))
        {
            <button type="submit" name="btn btn-primary btn-block" ><h6><b>ONAYLA</b></h6></button>
        }
        @using (Html.BeginForm("UpdateForm", "Manager", FormMethod.Post, new { FormId = Model.listForExpenses.First().FormID , Status = "Onaylanmadı" }))
        {
            <button type="submit" name="btn btn-primary btn-block" ><h6><b>REDDET</b></h6></button>
        }
    </div>
</body>
</html>

ExpensApp/ExpensApp.Presentation/Views/Manager/ManagerMainPage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ManagerMainPage</title>
</head>
<body>
    <div> 
        <br />
        @Html.ActionLink("Onay Bekleyen Masraf Formları", "ApprovingExpenseFormPage", "Manager")
        <br />
        @Html.ActionLink("Raporlar", "ManagerReportsPage", "Manager")
        <br />
        @Html.ActionLink("Çıkış Yap", "Logout", "Home");
    </div>
</body>
</html>

ExpensApp/ExpensApp.Presentation/Views/Manager/ManagerReportsPage.cshtml
@{
    Layout = null;
}
@model CommonArea.MultipleModel2
<!DOCTYPE html>

<html>
<head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="~/Content/css/GridSheetforFillExpenseFormPage.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>ManagerReportsPage</title>
</head>
<body>
    <div>
        <h1 align="center">YÖNETİCİ RAPOR SAYFASI</h1>
    </div>
    <div class="container">
        <div class="row col-md-6 col-md-offset-2 custyle">
            <table class="table table-striped custab">
                <tr>
                    <td>Form Tarihi/td>
                    <td>Çalışan Ad Soyad</td>
                    <td>Toplam Masraf Tutarı</td>
                    <td>Onay/Ödendi Durumu</td>
                </tr>
                @{
                    int counter = 0;
                    foreach (var item in Model.listForForms)
                    {
                        var item2 = Model.listForEmployees[counter];

                        <tr>
                            <td>@item.Date.ToString("dd/MM/yyyy")</td>
                            <td>@item2.Name @item2.Surname</td>
                            <td>@item.TotalAmount</td>
                            <td>@item.Status</td>
                        </tr>
                    }
                }
            </table>
        </div>
    </div>
</body>
</html>

ExpensApp/ExpensApp.Presentation/Views/Manager/OpenExpensePage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>OpenExpensePage</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>