ExpensApp/ExpensApp.Presentation/Controllers/StaffController.cs
using CommonArea;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExpensApp.Business;
using System.Dynamic;
using ExpensApp.Presentation.Filter;

namespace ExpensApp.Presentation.Controllers
{
    public class StaffController : Controller
    {
        List<SelectListItem> items = new List<SelectListItem>();
        static List<ExpenseCommon> expensesList = new List<ExpenseCommon>();
        static List<FormCommon> formList2 = new List<FormCommon>();
        StaffBusiness staff = new StaffBusiness();
        MultipleModel myModel = new MultipleModel();

        // GET: Staff
        [AuthFilter, AuthorityControlStaff]
        public ActionResult StaffMainPage()
        {
            return View();
        }

        [AuthFilter, AuthorityControlStaff]
        public ActionResult FillingExpenseFormPage()     //First expense operation
        {
            items.Add(new SelectListItem { Text = "Yemek", Value = "Yemek" });

            items.Add(new SelectListItem { Text = "Ulaşım", Value = "Ulaşım" });

            items.Add(new SelectListItem { Text = "Benzin", Value = "Benzin", Selected = true });

            items.Add(new SelectListItem { Text = "Diğer", Value = "Diğer" });

            ViewBag.Types = items;

            myModel.list = expensesList;
            myModel.expense = new ExpenseCommon();

            return View(myModel);
        }

        [HttpPost]
        public ActionResult FillingExpenseFormPage(MultipleModel entityModel)   //gride ekleme için dönüş
        {
            items.Add(new SelectListItem { Text = "Yemek", Value = "Yemek" });

            items.Add(new SelectListItem { Text = "Ulaşım", Value = "Ulaşım" });

            items.Add(new SelectListItem { Text = "Benzin", Value = "Benzin", Selected = true });

            items.Add(new SelectListItem { Text = "Diğer", Value = "Diğer" });

            ViewBag.Types = items;
            //myModel.list = expensesList;

            expensesList.Add(entityModel.expense);
            myModel.list = expensesList;
            //myModel.list.Add(entityModel.expense);

            return View(myModel);
        }

        [HttpPost]
        public ActionResult AddingExpensesToDataBase(MultipleModel model)
        {
            //staff.AddExpenseToForm(myModel.list, ((int)Session["EmployeeId"]));

            var sample = expensesList;
            staff.AddExpenseToForm(sample, ((int)Session["EmployeeId"]));
            return RedirectToAction("StaffMainPage");
        }


        [AuthFilter]
        public ActionResult ExpenseFormsPage()
        {
            return View();
        }


        [AuthFilter, AuthorityControlStaff]
        public ActionResult StaffReportsPage()
        {
            formList2 = staff.GetFilledFormsFromID((int) Session["EmployeeId"]);
            return View(formList2);
        }
    }
}

ExpensApp/ExpensApp.Presentation/Views/Staff/ExpenseFormsPage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ExpenseFormsPage</title>
</head>
<body>
    <div> 
        <h1>MASRAF FORMU DÜZENLEME SAYFASIDIR</h1>
    </div>
</body>
</html>

ExpensApp/ExpensApp.Presentation/Views/Staff/FillingExpenseFormPage.cshtml
@{
    Layout = null;
}
@model CommonArea.MultipleModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FillingExpenseFormPage</title>
    <script src="http://code.jquery.com/code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <link href="~/Content/css/GridSheetforFillExpenseFormPage.css" rel="stylesheet" />

    <script type="text/javascript">
        $(".form_datetime").datetimepicker({
            format: "dd MM yyyy - hh:ii"
        });
    </script> 
    <meta charset="utf-8">
    <title>JS Bin</title>
</head>
<body>
    <div>
        <h1>MASRAF FORMU DOLDURMA SAYFASIDIR</h1><br /><br /><br />

        @using (Html.BeginForm("FillingExpenseFormPage", "Staff", FormMethod.Post, new { @id = "FillForm" }))
        {
            <form type="Post">
                @*Taking Dropdown List data for expense type*@
                <div class="form-group">
                    <div class="form-label-group">
                        <p>Masraf Türü:</p>
                        @Html.DropDownListFor(model => model.expense.Type, new SelectList(ViewBag.Types, "Value", "Text"), new { @class = "form-control" })
                        <br />
                    </div>
                </div>

                @*Taking Datepicker data for expense date*@

                <p>Masraf Zamanı:</p>
                <div class="form-group">
                    <div>
                        @Html.TextBoxFor(model => model.expense.Date, new { @type = "date", @class = "form-control datepicker"})
                    </div>
                </div>

                @*Taking textbox data for expense explanation*@
                <div class="form-group">
                    <div class="form-label-group">
                        <p>Masraf Açıklaması:</p>
                        @Html.TextBoxFor(model => model.expense.Explanation, new { @class = "form-control", @placeholder = "Açıklama Giriniz", @required = "required", @autofocus = "autofocus" })
                        <br />
                    </div>
                </div>

                @*Taking textbox data for expense cost*@
                <div class="form-group">
                    <div class="form-label-group">
                        <p>Masraf Tutarı:</p>
                        @Html.TextBoxFor(model => model.expense.Cost, new { @type = "number", @placeholder = "Tutar Giriniz", @required = "required" })
                    </div>
                </div>
                <button type="submit" name="btn btn-primary btn-block" href="/FillingExpenseFormPage">Masraf Ekle</button>
            </form>
        }
        @*Printing expenses and total amount to the screen*@
        @{
                int TotalAmount = 0;
                if (Model.list != null)
                {
                <p align="center"><b>Masraflar:</b></p>
                <div class="container">
                    <div class="row col-md-6 col-md-offset-2 custyle">
                        <table class="table table-striped custab">
                            <tr>
                                <th>Masraf Türü</th>
                                <th>Masraf Zamanı</th>
                                <th>Masraf Açıklaması</th>
                                <th>Masraf Tutarı</th>
                            </tr>
                            @foreach (var item in Model.list)
            {
                                <tr>
                                    <td>@item.Type</td>
                                    <td>@item.Date.ToString("dd/MM/yyyy") </td>
                                    <td>@item.Explanation</td>
                                    <td>@item.Cost</td>
                                    @{
                    TotalAmount = TotalAmount + item.Cost;
                                        }
                                </tr>
                                        }
                        </table>
                    </div>
                </div>
                                        }
        }
        <br /><p align="center"><b>Total Amount : @TotalAmount</b></p>
    </div>
    <div>
        @using (Html.BeginForm("StaffMainPage", "Staff", FormMethod.Post, new { @id = "AddForm" }))
        {

            <button type="submit" name="btn btn-primary btn-block" href="/StaffMainPage"><h6><b>İPTAL</b></h6></button>
        }
        @using (Html.BeginForm("AddingExpensesToDatabase", "Staff", FormMethod.Post, new { @id = "AddForm" }))
        {      
            <button type="submit" name="btn btn-primary btn-block" href="/StaffMainPage"><h6><b>ONAYLA</b></h6></button>
        }
    </div>
</body>
</html>

ExpensApp/ExpensApp.Presentation/Views/Staff/StaffMainPage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>StaffMainPage</title>
</head>
<body>
    <div> 
        <br />
        @Html.ActionLink("Masraf Formu Doldur", "FillingExpenseFormPage","Staff")
        <br />
        @Html.ActionLink("Gönderilmiş Masraf Formları", "ExpenseFormsPage", "Staff")
        <br />
        @Html.ActionLink("Raporlar", "StaffReportsPage", "Staff")
        <br />
        @Html.ActionLink("Çıkış Yap", "Logout", "Home");
    </div>
</body>
</html>

ExpensApp/ExpensApp.Presentation/Views/Staff/StaffReportsPage.cshtml
@{
    Layout = null;
}
@model List<CommonArea.FormCommon>
<!DOCTYPE html>

<html>
<head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="~/Content/css/GridSheetforFillExpenseFormPage.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>StaffReportsPage</title>
</head>
<body>
    <div>
        <h1 align="center">RAPORLAR</h1>
    </div>
    <div class="container">
        <div class="row col-md-6 col-md-offset-2 custyle">
            <table class="table table-striped custab">
                <tr>
                    <td>Form Tarihi</td>
                    <td>Toplam Masraf Tutarı</td>
                    <td>Onay/Ödendi Durumu</td>
                </tr>
                @{
                    var list = Model;
                    foreach (var item in list)
                    {
                        <tr>
                            <td>@item.Date.ToString("dd/MM/yyyy")</td>
                            <td>@item.TotalAmount</td>
                            <td>@item.Status</td>
                        </tr>
                    }
                }
            </table>
        </div>
    </div>
</body>
</html>