ExpensApp/ExpensApp.Presentation/Controllers/AccountantController.cs
using CommonArea;
using ExpensApp.Business;
using ExpensApp.Presentation.Filter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExpensApp.Presentation.Controllers
{
    public class AccountantController : Controller
    {
        List<FormCommon> formList = new List<FormCommon>();
        List<EmployeeCommon> employeeList = new List<EmployeeCommon>();
        List<ExpenseCommon> expenseList = new List<ExpenseCommon>();
        ManagerBusiness manager = new ManagerBusiness();
        MultipleModel2 myModel = new MultipleModel2();

        [AuthFilter, AuthorityControlAccountant]
        public ActionResult AccountantMainPage()
        {
            return View();
        }

        [AuthFilter, AuthorityControlAccountant]
        public ActionResult PayingExpensePage()
        {

            formList = manager.GetForms();     //getting forms 
            employeeList = manager.GetEmployees(formList);   //getting employees

            myModel.listForForms = formList;
            myModel.listForEmployees = employeeList;

            return View(myModel);
        }

        [AuthFilter, AuthorityControlAccountant]
        public ActionResult AccountantReportsPage()
        {
            return View();
        }
    }
}

ExpensApp/ExpensApp.Presentation/Views/Accountant/AccountantMainPage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AccountantMainPage</title>
</head>
<body>
    <div> 
        <br />
        @Html.ActionLink("Ödeme Bekleyen Masraflar", "PayingExpensePage", "Accountant")
        <br />
        @Html.ActionLink("Raporlar", "AccountantReportsPage", "Accountant")
        <br />
        @Html.ActionLink("Çıkış Yap", "Logout", "Home");
    </div>
</body>
</html>

ExpensApp/ExpensApp.Presentation/Views/Accountant/AccountantReportsPage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AccountantReportsPage</title>
</head>
<body>
    <div> 
        <h1>MUHASEBECİ RAPOR SAYFASIDIR</h1>
    </div>
</body>
</html>

ExpensApp/ExpensApp.Presentation/Views/Accountant/PayingExpensePage.cshtml
@{
    Layout = null;
}
@model CommonArea.MultipleModel2
<!DOCTYPE html>

<html>
<head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="~/Content/css/GridSheetforFillExpenseFormPage.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>ApprovingExpenseFormPage</title>
    <script>
        $(document).ready(function() {
            $(document).on("click", "#formTable tbody tr", function() {
                alert(this.id);
    });
});
    </script>
</head>
<body>
    <div>
        <h1 align="center">ÖDEME BEKLEYEN MASRAFLAR</h1>
    </div>

    <div class="container">
        <div class="row col-md-6 col-md-offset-2 custyle">
            <table class="table table-striped custab" id="formTable">
                <tr>
                    <th>Form Tarihi</th>
                    <th>Çalışan Ad Soyad</th>
                    <th>Toplam Masraf Tutarı</th>
                </tr>
                @{
                    int counter = 0;
                    foreach (var item in Model.listForForms)
                    {
                        var item2 = Model.listForEmployees[counter];

                        <tr id="@item.FormID">
                            <td>@item.Date.ToString("dd/MM/yyyy")</td>
                            <td>@item2.Name @item2.Surname</td>
                            <td>@item.TotalAmount</td>
                        </tr>

                    }
                }
            </table>
        </div>
    </div>

</body>

</html>